name: Email on push
run-name: ${{ github.actor }} has pushed something
on: [push]
jobs:
  mail_on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3.12.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Kiri github actionilt
          body: Tere
          to: kristjan@kivikangur.eu
          from: Github actions
